packages:
  - packages/*

overrides:
  '@gqfn/cli': workspace:*
  '@gqfn/core': workspace:*
  '@gqfn/nuxt': workspace:*

ignoredBuiltDependencies:
  - better-sqlite3
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - unrs-resolver
